# Scope: Build and Push Docker Image

name: DockerPush

on: 
  workflow_dispatch:
    inputs:
      image:
        description: 'Name of Image to push'
        required: true
        type: choice
        options:
        - dotnet
        - pyspark
        - python
        - terraform
        - ubuntu
      version:
        description: 'Version of Image to push'
        required: false
        type: string
      tag:
        description: 'Image Tag (Version) to push'
        required: true
        type: string
        default: 'dev'

env:
  DEPLOY_IMAGE: ${{ github.event.inputs.image }}
  DEPLOY_VERSION: ${{ github.event.inputs.version }}


jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Set Image Version
      id: set_image_version
      run: |
        if [[ -z $DEPLOY_VERSION ]]; then
          echo "IMAGE_VERSION=$DEPLOY_IMAGE" >> "$GITHUB_OUTPUT";
        else
          echo "IMAGE_VERSION=$DEPLOY_IMAGE-$DEPLOY_VERSION" >> "$GITHUB_OUTPUT";
        fi
        echo $IMAGE_VERSION

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_ID }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./containers/${{ github.event.inputs.image }}/Dockerfile.${{ steps.set_image_version.outputs.IMAGE_VERSION }}
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        tags: ${{ secrets.DOCKER_HUB_ID }}/${{ steps.set_image_version.outputs.IMAGE_VERSION }}:${{ github.event.inputs.tag }}
